# Generated by Django 5.1.6 on 2025-02-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
