# Generated by Django 5.1.4 on 2025-03-31 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Application', '0002_registration_audio_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_new', models.FileField(blank=True, null=True, upload_to='audios_generated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add', to='Sign_Application.registration')),
            ],
        ),
    ]
